version: 2

project_name: registry-ui

builds:
  - id: registry-ui-linux
    main: .
    binary: registry-ui
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -buildid= -X main.version={{ .Version }}

archives:
  - id: registry-ui-linux
    ids:
      - registry-ui-linux
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
